### ISSUE TITLE
Todo page update(reformat cards, make CTA buttons have primary blue color)

### ISSUE THREAD

**Issue by Stephboss9** [Course-Hero-3/MotivateMe#109]
- [x] Make font size bigger for words on todo card, also put all information onto one line to save screen real estate
- [x] get rid of the create button(not functionality), and replace it with a "+" image button
- [x] allows tasks to be filtered by essays
- [x] make forms look fancier and apply any other formatting
