### ISSUE TITLE
change color of tasks in todo component

### ISSUE THREAD

**Issue by StaticMaster** [Course-Hero-3/MotivateMe#186]
- [x] Get rid of colors in dark mode and make all cards one color. 
- [x] Change dark mode blue text inside odal to white
- [x] Make red errors in dark mode white
